"""Docker-free quickstart: scaffold a minimal config.yaml for a new project.

Auto-detects target locales from existing localization files and writes a small,
generic config that defaults to the git translation source and OpenAI
gpt-4o-mini/gpt-4o. The goal is a 5-minute first run without editing a 400-line
example by hand.

Usage::

    python -m localize.init_config --input-folder path/to/i18n --target-project-root .
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Tuple

import yaml

from localize.localization_formats import (
    JAVA_PROPERTIES_FORMAT,
    LocalizationFormat,
    list_localization_formats,
    load_localization_format,
)
from localize.localization_layouts import (
    SUFFIX_LAYOUT,
    LocalizationLayout,
    load_localization_layout,
)

# Human-readable names for common locale codes; unknown codes fall back to the code.
_LOCALE_NAMES: Dict[str, str] = {
    "af_ZA": "Afrikaans", "ca": "Catalan", "cs": "Czech", "de": "German",
    "el": "Greek", "es": "Spanish", "fi": "Finnish", "fr": "French",
    "ga": "Irish", "ha": "Hausa", "hr": "Croatian", "id": "Indonesian",
    "it": "Italian", "ja": "Japanese", "ko": "Korean", "mk": "Macedonian",
    "nl": "Dutch", "no": "Norwegian", "pcm": "Nigerian Pidgin", "pl": "Polish",
    "pt": "Portuguese", "pt_BR": "Brazilian Portuguese", "ru": "Russian",
    "sl": "Slovenian", "sr": "Serbian", "sv": "Swedish", "ta": "Tamil",
    "th": "Thai", "tr": "Turkish", "uk": "Ukrainian", "vi": "Vietnamese",
    "yo": "Yoruba", "zh": "Chinese", "zh-Hans": "Simplified Chinese",
    "zh-Hant": "Traditional Chinese",
}

_HEADER = (
    "# Minimal configuration generated by `python -m localize.init_config`.\n"
    "# Review the detected paths/locales, then run localize check and a dry run.\n"
    "# See config.example.yaml for the full set of optional settings.\n"
)


@dataclass(frozen=True)
class DetectedProjectLayout:
    """Autodetected localization layout for a repository."""

    input_folder: str
    localization_profiles: List[Tuple[LocalizationFormat, LocalizationLayout]]
    locales: List[Dict[str, str]]


def code_to_name(code: str) -> str:
    """Map a locale code to a human-readable name, falling back to the code."""
    return _LOCALE_NAMES.get(code, code)


def _resolve_localization_format(raw_value: object) -> LocalizationFormat:
    if isinstance(raw_value, LocalizationFormat):
        return raw_value
    try:
        return load_localization_format(raw_value)
    except ValueError as exc:
        raise ValueError(str(exc)) from exc


def _resolve_localization_layout(raw_value: object, source_locale: str = "en") -> LocalizationLayout:
    if isinstance(raw_value, LocalizationLayout):
        return raw_value
    try:
        return load_localization_layout(raw_value, source_locale=source_locale)
    except ValueError as exc:
        raise ValueError(str(exc)) from exc


def parse_localization_profile_spec(
    spec: str,
    source_locale: str = "en",
) -> Tuple[LocalizationFormat, LocalizationLayout]:
    """Parse ``FORMAT:LAYOUT`` shorthand used by ``localize init``."""
    if ":" not in spec:
        raise ValueError("Localization profile must use FORMAT:LAYOUT syntax.")
    raw_format, raw_layout = (part.strip() for part in spec.split(":", 1))
    if not raw_format or not raw_layout:
        raise ValueError("Localization profile must use FORMAT:LAYOUT syntax.")
    return (
        _resolve_localization_format(raw_format),
        _resolve_localization_layout(raw_layout, source_locale),
    )


def detect_locales(
    input_folder: str,
    source_locale: str = "en",
    localization_format: object = JAVA_PROPERTIES_FORMAT.id,
    localization_layout: object = SUFFIX_LAYOUT.id,
) -> List[Dict[str, str]]:
    """Detect target locales from localization files in ``input_folder``.

    Returns a sorted, de-duplicated list of ``{"code", "name"}`` dicts, excluding
    the source locale. Returns an empty list if the folder does not exist.
    """
    fmt = _resolve_localization_format(localization_format)
    layout = _resolve_localization_layout(localization_layout, source_locale)
    if not os.path.isdir(input_folder):
        return []
    codes = set()
    # Walk recursively, matching how the pipeline discovers localization files.
    for root, _dirs, files in os.walk(input_folder):
        for entry in files:
            if not fmt.is_supported_file(entry):
                continue
            rel_path = os.path.relpath(os.path.join(root, entry), input_folder)
            code = layout.extract_locale(rel_path, _candidate_locale_codes(rel_path, fmt), fmt)
            if code and code != source_locale:
                codes.add(code)
    return [{"code": code, "name": code_to_name(code)} for code in sorted(codes)]


def detect_locales_for_profiles(
    input_folder: str,
    source_locale: str,
    localization_profiles: Iterable[Tuple[object, object]],
) -> List[Dict[str, str]]:
    """Detect target locales from several configured format/layout profiles."""
    codes: set[str] = set()
    for raw_format, raw_layout in localization_profiles:
        detected = detect_locales(
            input_folder,
            source_locale=source_locale,
            localization_format=raw_format,
            localization_layout=raw_layout,
        )
        codes.update(locale["code"] for locale in detected)
    return [{"code": code, "name": code_to_name(code)} for code in sorted(codes)]


def detect_localization_profiles(
    input_folder: str,
    source_locale: str = "en",
) -> List[Tuple[LocalizationFormat, LocalizationLayout]]:
    """Detect format/layout profiles that have source and target locale files."""
    profiles: List[Tuple[LocalizationFormat, LocalizationLayout]] = []
    for localization_format in list_localization_formats().values():
        for layout_id in ("suffix", "locale_directory", "locale_filename"):
            layout = _resolve_localization_layout(layout_id, source_locale)
            locales = detect_locales(
                input_folder,
                source_locale=source_locale,
                localization_format=localization_format,
                localization_layout=layout,
            )
            if locales and _has_source_file(input_folder, localization_format, layout):
                profiles.append((localization_format, layout))
    return profiles


def detect_project_layout(
    target_project_root: str,
    source_locale: str = "en",
) -> Optional[DetectedProjectLayout]:
    """Detect the best input folder, profiles, and locales for a repository."""
    if not os.path.isdir(target_project_root):
        return None

    roots = _discover_localization_roots(target_project_root, source_locale)
    if not roots:
        return None

    input_folder_abs = os.path.commonpath(sorted(roots))
    profiles = detect_localization_profiles(input_folder_abs, source_locale=source_locale)
    if not profiles:
        return None

    locales = detect_locales_for_profiles(
        input_folder_abs,
        source_locale=source_locale,
        localization_profiles=profiles,
    )
    return DetectedProjectLayout(
        input_folder=_relative_posix_path(input_folder_abs, target_project_root),
        localization_profiles=profiles,
        locales=locales,
    )


_LOCALE_CODE_RE = re.compile(r"^[A-Za-z]{2,3}(?:[-_][A-Za-z0-9]{2,8})*$")


def _candidate_locale_codes(relative_path: str, localization_format: LocalizationFormat) -> List[str]:
    """Return broad locale candidates for autodetection before config exists."""
    candidates: set[str] = set()
    basename = os.path.basename(relative_path)
    suffix_code = localization_format.extract_locale_suffix(basename)
    if suffix_code:
        candidates.add(suffix_code)
    stem, _extension = os.path.splitext(basename)
    if _looks_like_locale_code(stem):
        candidates.add(stem)
    for segment in relative_path.replace("\\", "/").split("/")[:-1]:
        if _looks_like_locale_code(segment):
            candidates.add(segment)
    return sorted(candidates, key=len, reverse=True)


def _looks_like_locale_code(value: str) -> bool:
    return bool(value) and bool(_LOCALE_CODE_RE.fullmatch(value))


def _has_source_file(
    input_folder: str,
    localization_format: LocalizationFormat,
    localization_layout: LocalizationLayout,
) -> bool:
    if not os.path.isdir(input_folder):
        return False
    for root, _dirs, files in os.walk(input_folder):
        for entry in files:
            if not localization_format.is_supported_file(entry):
                continue
            rel_path = os.path.relpath(os.path.join(root, entry), input_folder)
            if localization_layout.is_source_file(
                rel_path,
                [localization_layout.source_locale],
                localization_format,
            ):
                return True
    return False


def _discover_localization_roots(target_project_root: str, source_locale: str) -> List[str]:
    roots: set[str] = set()
    formats = tuple(list_localization_formats().values())
    for root, _dirs, files in os.walk(target_project_root):
        file_set = set(files)
        for entry in files:
            path = os.path.join(root, entry)
            rel_path = os.path.relpath(path, target_project_root)
            rel_parts = rel_path.replace("\\", "/").split("/")
            for localization_format in formats:
                if not localization_format.is_supported_file(entry):
                    continue
                _collect_suffix_root(roots, root, entry, file_set, localization_format, source_locale)
                _collect_locale_filename_root(
                    roots,
                    root,
                    entry,
                    file_set,
                    localization_format,
                    source_locale,
                )
                _collect_locale_directory_root(
                    roots,
                    target_project_root,
                    rel_parts,
                    localization_format,
                    source_locale,
                )
    return sorted(roots)


def _collect_suffix_root(
    roots: set[str],
    root: str,
    entry: str,
    file_set: set[str],
    localization_format: LocalizationFormat,
    source_locale: str,
) -> None:
    locale = localization_format.extract_locale_suffix(entry)
    if not locale or locale == source_locale:
        return
    source_name = localization_format.source_filename(entry, [locale])
    if source_name in file_set:
        roots.add(root)


def _collect_locale_filename_root(
    roots: set[str],
    root: str,
    entry: str,
    file_set: set[str],
    localization_format: LocalizationFormat,
    source_locale: str,
) -> None:
    stem, _extension = os.path.splitext(entry)
    if not _looks_like_locale_code(stem) or stem == source_locale:
        return
    if f"{source_locale}{localization_format.file_extension}" in file_set:
        roots.add(root)


def _collect_locale_directory_root(
    roots: set[str],
    target_project_root: str,
    rel_parts: List[str],
    localization_format: LocalizationFormat,
    source_locale: str,
) -> None:
    filename = rel_parts[-1]
    for index, segment in enumerate(rel_parts[:-1]):
        if not _looks_like_locale_code(segment) or segment == source_locale:
            continue
        source_parts = [*rel_parts[:index], source_locale, *rel_parts[index + 1:]]
        source_path = os.path.join(target_project_root, *source_parts)
        if os.path.exists(source_path) and localization_format.is_supported_file(filename):
            root_parts = rel_parts[:index]
            roots.add(os.path.join(target_project_root, *root_parts) if root_parts else target_project_root)


def _relative_posix_path(path: str, root: str) -> str:
    rel_path = os.path.relpath(path, root)
    if rel_path == ".":
        return "."
    return rel_path.replace(os.sep, "/")


def _resolve_input_folder_for_detection(input_folder: str, target_project_root: str) -> str:
    if os.path.isabs(input_folder):
        return input_folder
    return os.path.join(target_project_root, input_folder)


def build_config(
    *,
    target_project_root: str,
    input_folder: str,
    locales: List[Dict[str, str]],
    model_name: str = "gpt-4o-mini",
    review_model_name: str = "gpt-4o",
    api_base_url: Optional[str] = None,
    localization_format: object = JAVA_PROPERTIES_FORMAT.id,
    localization_layout: object = SUFFIX_LAYOUT.id,
    localization_profiles: Optional[Iterable[Tuple[object, object]]] = None,
    source_locale: str = "en",
    dry_run: bool = True,
) -> Dict[str, object]:
    """Build a minimal configuration dict for a new project (git source by default)."""
    config: Dict[str, object] = {
        "target_project_root": target_project_root,
        "input_folder": input_folder,
        "translation_source": "git",
        "model_name": model_name,
        "review_model_name": review_model_name,
        "dry_run": dry_run,
        "supported_locales": locales,
    }
    if localization_profiles:
        config["localization_formats"] = [
            _profile_config_entry(raw_format, raw_layout, source_locale)
            for raw_format, raw_layout in localization_profiles
        ]
    else:
        fmt = _resolve_localization_format(localization_format)
        layout = _resolve_localization_layout(localization_layout, source_locale)
        config["localization_format"] = fmt.id
        config["localization_layout"] = _layout_config(layout)
    if api_base_url:
        config["api_base_url"] = api_base_url
    return config


def _layout_config(layout: LocalizationLayout) -> Dict[str, str]:
    return {
        "id": layout.id,
        "source_locale": layout.source_locale,
    }


def _profile_config_entry(
    raw_format: object,
    raw_layout: object,
    source_locale: str,
) -> Dict[str, object]:
    fmt = _resolve_localization_format(raw_format)
    layout = _resolve_localization_layout(raw_layout, source_locale)
    return {
        "id": fmt.id,
        "layout": _layout_config(layout),
    }


def render_config(config: Dict[str, object]) -> str:
    """Render a config dict to YAML text with an explanatory header comment."""
    body = yaml.safe_dump(config, sort_keys=False, allow_unicode=True, default_flow_style=False)
    return f"{_HEADER}\n{body}"


def write_config(path: str, content: str, overwrite: bool = False) -> None:
    """Write ``content`` to ``path``; refuse to clobber an existing file unless ``overwrite``."""
    if os.path.exists(path) and not overwrite:
        raise FileExistsError(
            f"{path} already exists. Re-run with --overwrite to replace it."
        )
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def _parse_args(argv: Optional[List[str]]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="python -m localize.init_config",
        description="Scaffold a minimal config.yaml by detecting locales from localization files.",
    )
    parser.add_argument("--input-folder", default=None,
                        help="Folder containing your localization files.")
    parser.add_argument("--localization-format", default=None,
                        help="Built-in localization format id (java_properties or json).")
    parser.add_argument("--localization-layout", default=None,
                        help="Built-in localization layout id (suffix, locale_directory, or locale_filename).")
    parser.add_argument("--localization-profile", action="append", default=[],
                        help="Mixed-project profile as FORMAT:LAYOUT. Repeat for each profile.")
    parser.add_argument("--target-project-root", default=".",
                        help="Path to the git repository root (default: current directory).")
    parser.add_argument("--source-locale", default="en",
                        help="Source language code to exclude from targets (default: en).")
    parser.add_argument("--output", default="config.yaml",
                        help="Where to write the config (default: config.yaml).")
    parser.add_argument("--api-base-url", default=None,
                        help="OpenAI-compatible endpoint, e.g. http://localhost:11434/v1 for Ollama.")
    parser.add_argument("--overwrite", action="store_true",
                        help="Overwrite an existing config file.")
    return parser.parse_args(argv)


def main(argv: Optional[List[str]] = None) -> int:
    args = _parse_args(argv)
    try:
        explicit_profiles = [
            parse_localization_profile_spec(spec, source_locale=args.source_locale)
            for spec in args.localization_profile
        ]
        explicit_single_profile = args.localization_format is not None or args.localization_layout is not None
        if explicit_profiles:
            localization_format = JAVA_PROPERTIES_FORMAT
            localization_layout = _resolve_localization_layout(SUFFIX_LAYOUT.id, args.source_locale)
        else:
            localization_format = _resolve_localization_format(
                args.localization_format or JAVA_PROPERTIES_FORMAT.id
            )
            localization_layout = _resolve_localization_layout(
                args.localization_layout or SUFFIX_LAYOUT.id,
                args.source_locale,
            )
    except ValueError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    input_folder = args.input_folder
    autodetected_profiles: List[Tuple[LocalizationFormat, LocalizationLayout]] = []
    if input_folder is None:
        detected = detect_project_layout(args.target_project_root, source_locale=args.source_locale)
        if detected is None:
            print(
                "Error: could not detect localization files. Re-run with --input-folder "
                "and, if needed, --localization-format/--localization-layout.",
                file=sys.stderr,
            )
            return 1
        input_folder = detected.input_folder
        if explicit_profiles:
            locales = detect_locales_for_profiles(
                _resolve_input_folder_for_detection(input_folder, args.target_project_root),
                source_locale=args.source_locale,
                localization_profiles=explicit_profiles,
            )
        elif explicit_single_profile:
            locales = detect_locales(
                _resolve_input_folder_for_detection(input_folder, args.target_project_root),
                source_locale=args.source_locale,
                localization_format=localization_format,
                localization_layout=localization_layout,
            )
        else:
            autodetected_profiles = detected.localization_profiles
            locales = detected.locales
    elif not explicit_profiles and not explicit_single_profile:
        autodetected_profiles = detect_localization_profiles(
            _resolve_input_folder_for_detection(input_folder, args.target_project_root),
            source_locale=args.source_locale,
        )
        locales = detect_locales_for_profiles(
            _resolve_input_folder_for_detection(input_folder, args.target_project_root),
            source_locale=args.source_locale,
            localization_profiles=autodetected_profiles,
        ) if autodetected_profiles else []
    elif explicit_profiles:
        locales = detect_locales_for_profiles(
            _resolve_input_folder_for_detection(input_folder, args.target_project_root),
            source_locale=args.source_locale,
            localization_profiles=explicit_profiles,
        )
    else:
        locales = detect_locales(
            _resolve_input_folder_for_detection(input_folder, args.target_project_root),
            source_locale=args.source_locale,
            localization_format=localization_format,
            localization_layout=localization_layout,
        )
    localization_profiles = explicit_profiles
    if autodetected_profiles:
        if len(autodetected_profiles) == 1:
            localization_format, localization_layout = autodetected_profiles[0]
        else:
            localization_profiles = autodetected_profiles
    if not locales and not localization_profiles and not autodetected_profiles:
        locales = detect_locales(
            _resolve_input_folder_for_detection(input_folder, args.target_project_root),
            source_locale=args.source_locale,
            localization_format=localization_format,
            localization_layout=localization_layout,
        )
    if not locales:
        print(
            f"Warning: no target locales detected in '{input_folder}'. "
            "Add supported_locales to the generated config manually.",
            file=sys.stderr,
        )
    config = build_config(
        target_project_root=args.target_project_root,
        input_folder=input_folder,
        locales=locales,
        api_base_url=args.api_base_url,
        localization_format=localization_format,
        localization_layout=localization_layout,
        localization_profiles=localization_profiles or None,
        source_locale=args.source_locale,
    )
    try:
        write_config(args.output, render_config(config), overwrite=args.overwrite)
    except FileExistsError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"Error: could not write '{args.output}': {exc}", file=sys.stderr)
        return 1

    detected = ", ".join(loc["code"] for loc in locales) or "(none)"
    print(f"Wrote {args.output}")
    print(f"Detected target locales: {detected}")
    print("Next steps:")
    print("  1. Review the locales and paths in the generated config.")
    print(f"  2. Run: localize check --config {args.output}")
    print(f"  3. Preview: localize run --dry-run --config {args.output}")
    print("  4. Set dry_run: false and configure OPENAI_API_KEY or api_base_url for real runs.")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
