"""Docker-free quickstart: scaffold a minimal config.yaml for a new project.

Auto-detects target locales from existing ``*_<locale>.properties`` files and
writes a small, generic config that defaults to the git translation source and
OpenAI gpt-4o-mini/gpt-4o. The goal is a 5-minute first run without editing a
400-line example by hand.

Usage::

    python -m src.init_config --input-folder path/to/i18n --target-project-root .
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Dict, List, Optional

import yaml

from src.locale_utils import extract_locale_suffix

# Human-readable names for common locale codes; unknown codes fall back to the code.
_LOCALE_NAMES: Dict[str, str] = {
    "af_ZA": "Afrikaans", "ca": "Catalan", "cs": "Czech", "de": "German",
    "el": "Greek", "es": "Spanish", "fi": "Finnish", "fr": "French",
    "ga": "Irish", "ha": "Hausa", "hr": "Croatian", "id": "Indonesian",
    "it": "Italian", "ja": "Japanese", "ko": "Korean", "mk": "Macedonian",
    "nl": "Dutch", "no": "Norwegian", "pcm": "Nigerian Pidgin", "pl": "Polish",
    "pt": "Portuguese", "pt_BR": "Brazilian Portuguese", "ru": "Russian",
    "sl": "Slovenian", "sr": "Serbian", "sv": "Swedish", "ta": "Tamil",
    "th": "Thai", "tr": "Turkish", "uk": "Ukrainian", "vi": "Vietnamese",
    "yo": "Yoruba", "zh": "Chinese", "zh-Hans": "Simplified Chinese",
    "zh-Hant": "Traditional Chinese",
}

_HEADER = (
    "# Minimal configuration generated by `python -m src.init_config`.\n"
    "# Edit the paths and review the detected locales, then run a translation.\n"
    "# See config.example.yaml for the full set of optional settings.\n"
)


def code_to_name(code: str) -> str:
    """Map a locale code to a human-readable name, falling back to the code."""
    return _LOCALE_NAMES.get(code, code)


def detect_locales(input_folder: str, source_locale: str = "en") -> List[Dict[str, str]]:
    """Detect target locales from ``*_<locale>.properties`` files in ``input_folder``.

    Returns a sorted, de-duplicated list of ``{"code", "name"}`` dicts, excluding
    the source locale. Returns an empty list if the folder does not exist.
    """
    if not os.path.isdir(input_folder):
        return []
    codes = set()
    # Walk recursively, matching how the pipeline discovers .properties files.
    for _root, _dirs, files in os.walk(input_folder):
        for entry in files:
            code = extract_locale_suffix(entry)
            if code and code != source_locale:
                codes.add(code)
    return [{"code": code, "name": code_to_name(code)} for code in sorted(codes)]


def build_config(
    *,
    target_project_root: str,
    input_folder: str,
    locales: List[Dict[str, str]],
    model_name: str = "gpt-4o-mini",
    review_model_name: str = "gpt-4o",
    api_base_url: Optional[str] = None,
) -> Dict[str, object]:
    """Build a minimal configuration dict for a new project (git source by default)."""
    config: Dict[str, object] = {
        "target_project_root": target_project_root,
        "input_folder": input_folder,
        "translation_source": "git",
        "model_name": model_name,
        "review_model_name": review_model_name,
        "dry_run": False,
        "supported_locales": locales,
    }
    if api_base_url:
        config["api_base_url"] = api_base_url
    return config


def render_config(config: Dict[str, object]) -> str:
    """Render a config dict to YAML text with an explanatory header comment."""
    body = yaml.safe_dump(config, sort_keys=False, allow_unicode=True, default_flow_style=False)
    return f"{_HEADER}\n{body}"


def write_config(path: str, content: str, overwrite: bool = False) -> None:
    """Write ``content`` to ``path``; refuse to clobber an existing file unless ``overwrite``."""
    if os.path.exists(path) and not overwrite:
        raise FileExistsError(
            f"{path} already exists. Re-run with --overwrite to replace it."
        )
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def _parse_args(argv: Optional[List[str]]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="python -m src.init_config",
        description="Scaffold a minimal config.yaml by detecting locales from .properties files.",
    )
    parser.add_argument("--input-folder", required=True,
                        help="Folder containing your *.properties files.")
    parser.add_argument("--target-project-root", default=".",
                        help="Path to the git repository root (default: current directory).")
    parser.add_argument("--source-locale", default="en",
                        help="Source language code to exclude from targets (default: en).")
    parser.add_argument("--output", default="config.yaml",
                        help="Where to write the config (default: config.yaml).")
    parser.add_argument("--api-base-url", default=None,
                        help="OpenAI-compatible endpoint, e.g. http://localhost:11434/v1 for Ollama.")
    parser.add_argument("--overwrite", action="store_true",
                        help="Overwrite an existing config file.")
    return parser.parse_args(argv)


def main(argv: Optional[List[str]] = None) -> int:
    args = _parse_args(argv)
    locales = detect_locales(args.input_folder, source_locale=args.source_locale)
    if not locales:
        print(
            f"Warning: no target locales detected in '{args.input_folder}'. "
            "Add supported_locales to the generated config manually.",
            file=sys.stderr,
        )
    config = build_config(
        target_project_root=args.target_project_root,
        input_folder=args.input_folder,
        locales=locales,
        api_base_url=args.api_base_url,
    )
    try:
        write_config(args.output, render_config(config), overwrite=args.overwrite)
    except FileExistsError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"Error: could not write '{args.output}': {exc}", file=sys.stderr)
        return 1

    detected = ", ".join(loc["code"] for loc in locales) or "(none)"
    print(f"Wrote {args.output}")
    print(f"Detected target locales: {detected}")
    print("Next steps:")
    print("  1. Review the locales and paths in the generated config.")
    print("  2. Set OPENAI_API_KEY (or configure api_base_url for a local Ollama server).")
    print("  3. Run: ./run-local-translation.sh " + args.output)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
